image: node:10.15.3

pipelines:
  branches:
      master:
      - step:
            name: Publish
            deployment: production
            script:
              - npm version minor -m "Upgrade to %s [skip ci]"
              - pipe: atlassian/npm-publish:0.3.2
                variables:
                   NPM_TOKEN: $NPM_TOKEN